version: '3.7'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: joplin
      POSTGRES_USER: joplin
      POSTGRES_DB: joplin
    volumes:
      # TODO: mount in data partition? Backups?
      - /home/sthinds/Volumes/joplin:/var/lib/postgresql/data

  app:
    image: joplin/server:latest
    restart: always
    depends_on:
      - db
    ports:
      - "22300:22300"
    environment:
      APP_PORT: 22300
      APP_BASE_URL: "https://joplin.sth144.duckdns.org"
      TRUST_PROXY: 1
      DB_CLIENT: pg
      POSTGRES_PASSWORD: joplin
      POSTGRES_DATABASE: joplin
      POSTGRES_USER: joplin
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      APP_ADMIN_EMAIL: ${ADMIN_EMAIL}
      APP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      
