version: "2.4"
services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    user: "$UID:$GID"
    container_name: grafana
    depends_on:
      - prometheus
    network_mode: "host"
    #ports:
    #  - "3000:3000"
    volumes:
      - /home/sthinds/Volumes/grafana:/var/lib/grafana
  telegraf:
    image: telegraf:1.16
    container_name: telegraf
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    # links:
    #   - influxdb
    depends_on:
      - influxdb
    #ports:
    #  - 8092:8092/udp
    #  - 8094:8094
    #  - 8125:8125/udp
    #- 8086:8086
    network_mode: "host"
  chronograf:
    image: chronograf:latest
    ports: 
      - '127.0.0.1:8888:8888'
    volumes:
      - /home/sthinds/Volumes/chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://127.0.0.1:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
  prometheus:
    image: prom/prometheus:latest
    restart: always
    user: "$UID:$GID"
    container_name: prometheus
    network_mode: "host"
    #ports:
    #  - 9090:9090
    command: --web.enable-admin-api --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.retention.time=30d
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/sthinds/Volumes/prometheus:/prometheus
    privileged: true
  influxdb:
    image: influxdb:1.8.4
    restart: unless-stopped
    #ports:
    #  - 8086:8086
    volumes:
      - /home/sthinds/Volumes/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      # TODO: hide these
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    network_mode: "host"  
  loki:
    #image: grafana/loki:2.0.0
    image: grafana/loki:latest
    restart: always
    #ports:
    #  - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    network_mode: host
    volumes:
      - ./config/loki-config.yaml:/etc/loki/config.yaml
      - /home/sthinds/Volumes/loki:/data/loki
  promtail:
    #image: grafana/promtail:2.0.0
    image: grafana/promtail:latest
    restart: always
    ports: 
      - 10080:9080
    volumes:
      - /etc/promtail/:/etc/promtail/
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail.yaml
  pushgateway:
    image: prom/pushgateway:v1.0.1
    restart: always
    command:
      - --persistence.file=/data/pushgateway.data
      - --persistence.interval=1h
    expose:
      - 9091
    ports:
      - 9091:9091
    volumes: 
      - /home/sthinds/Volumes/pushgateway:/data
