version: "3"

services:
  db:
    image: mariadb
    container_name: nextcloud-mariadb
    ports:
      - 3306:3306
    volumes:
      - /home/sthinds/Volumes/nextcloud/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - .env.MYSQL_ROOT_PASSWORD
      - .env.MYSQL_PASSWORD
    restart: unless-stopped
  
  redis:
    image: redis:4.0-alpine
    restart: always
    command: redis-server --requirePass "password"
    volumes:
      - /home/sthinds/Volumes/nextcloud/redis:/var/lib/redis

  app:
    image: sthinds/nextcloud:latest
    container_name: nextcloud-app
    ports:
      - 9443:443
      - 9080:80
    depends_on:
      - db
      - redis
    volumes:
      - ./config:/var/www/html/config
      - /home/sthinds/Volumes/nextcloud/app:/var/www/html
      - /home/sthinds/Volumes/nextcloud/custom_apps:/var/www/html/custom_apps
      - /home/sthinds/Volumes/nextcloud/data:/var/www/html/data
      - /home/sthinds/Volumes/nextcloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=sthinds144.duckdns.org
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=password
    restart: unless-stopped

volumes:
  nextcloud:
  db:
