version: "3.3"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - "11443:443"
      - "11080:80"
      - "11022:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    depends_on:
      - postgres
      - redis

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    volumes:
      - './runner:/etc/gitlab-runner'
    command: ["run", "--user=gitlab-runner", "--working-directory=/home/gitlab-runner"]

  postgresql:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlabhq_production
    volumes:
      - ./postgresql:/var/lib/postgresql

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis:/data
