version: "3.7"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
#    networks:
#      - gitlab-network
    restart: always
    ports:
      - "11443:443"
      #- "11080:80"
      - "11080:11080"
      - "11022:22"
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'http://gitlab:11080'
    #    gitlab_rails['gitlab_shell_ssh_port'] = 2224
    volumes:
      - /home/sthinds/Volumes/gitlab/config:/etc/gitlab
      - /home/sthinds/Volumes/gitlab/logs:/var/log/gitlab
      - /home/sthinds/Volumes/gitlab/data:/var/opt/gitlab
      - /home/sthinds/.ssh:/root/.ssh
    depends_on:
      - postgresql
      - redis

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
#    networks:
#      - gitlab-network
    network_mode: host
    restart: always
    volumes:
      - ./config/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    command: ["run", "--user=gitlab-runner", "--working-directory=/home/gitlab-runner"]

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlabhq_production
    volumes:
      - /home/sthinds/Volumes/gitlab/postgresql:/var/lib/postgresql

  redis:
    image: redis:latest
    restart: always
    volumes:
      - /home/sthinds/Volumes/gitlab/redis:/data

networks:
  gitlab-network:
    driver: bridge

