version: "3.8"

services:
  redis:
    image: redis:7
    restart: always
    volumes:
      - /home/sthinds/Volumes/gitlab/redis:/data
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlabpass
      POSTGRES_DB: gitlabhq_production
    volumes:
      - /home/sthinds/Volumes/gitlab/postgresql:/var/lib/postgresql/data
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.245:11080'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlabpass'
        gitlab_rails['redis_host'] = 'redis'
        redis['enable'] = false
        postgresql['enable'] = false    
    ports:
      - 11080:80
      - 11443:443
      - 11022:22
    depends_on:
      - redis
      - postgres
    volumes:
      - ./config:/etc/gitlab
      - /home/sthinds/Volumes/gitlab/logs:/var/log/gitlab
      - /home/sthinds/Volumes/gitlab/data:/var/opt/gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - ./config/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
