{
 "title": "Resource Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gpu",
    "query": {
     "query": "label_values(nvidia_smi_index, uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_openmediavault\"} - node_boot_time_seconds{job=\"node_exporter_openmediavault\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_openmediavault\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_openmediavault\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_openmediavault\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Top CPU Consumers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, cpu_usage{job=\"node_exporter_openmediavault\"})",
     "legendFormat": "{{process}} ({{pid}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_openmediavault\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}",
     "legendFormat": "{{ chip }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_openmediavault\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_openmediavault\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_openmediavault\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_openmediavault\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_openmediavault\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_openmediavault\"} - node_memory_MemFree_bytes{job=\"node_exporter_openmediavault\"} - (node_memory_Cached_bytes{job=\"node_exporter_openmediavault\"} + node_memory_Buffers_bytes{job=\"node_exporter_openmediavault\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_openmediavault\"} + node_memory_Buffers_bytes{job=\"node_exporter_openmediavault\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_openmediavault\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_openmediavault\"} - node_memory_SwapFree_bytes{job=\"node_exporter_openmediavault\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Top Memory Consumers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, memory_usage{job=\"node_exporter_openmediavault\"})",
     "legendFormat": "{{process}} ({{pid}})"
    }
   ]
  },
  {
   "title": "Disk (O)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/srv/dev-disk-by-label-data\",fstype!=\"rootfs\",job=\"node_exporter_openmediavault\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/srv/dev-disk-by-label-data\",fstype!=\"rootfs\",job=\"node_exporter_openmediavault\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_openmediavault\",device!~'rootfs',mountpoint=\"/srv/dev-disk-by-label-data\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_openmediavault\",device!~'rootfs',mountpoint=\"/srv/dev-disk-by-label-data\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_openmediavault\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_main\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "Plex",
   "type": "logs",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "{container_name=\"plex\"}"
    }
   ]
  },
  {
   "title": "Nextcloud",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{host=\"openmediavault\", container_name=\"nextcloud-app\"}"
    }
   ]
  },
  {
   "title": "NGINX",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "{host=\"openmediavault\", container_name=\"nginx\"}"
    }
   ]
  },
  {
   "title": "Gateway Raspberry Pi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_RPi_main\"} - node_boot_time_seconds{job=\"node_exporter_RPi_main\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_main\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_main\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_main\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Top CPU Consumers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, cpu_usage{job=\"node_exporter_RPi_main\"})",
     "legendFormat": "{{process}} ({{pid}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_RPi_main\", chip=\"thermal_thermal_zone0\", sensor=\"temp0\"}",
     "legendFormat": "{{ chip }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_RPi_main\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_RPi_main\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_RPi_main\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_main\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_main\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_main\"} - node_memory_MemFree_bytes{job=\"node_exporter_RPi_main\"} - (node_memory_Cached_bytes{job=\"node_exporter_RPi_main\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_main\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_RPi_main\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_main\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_RPi_main\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_RPi_main\"} - node_memory_SwapFree_bytes{job=\"node_exporter_RPi_main\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Top Memory Consumers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, memory_usage{job=\"node_exporter_RPi_main\"})",
     "legendFormat": "{{process}} ({{pid}})"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_main\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_main\"})"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_RPi_main\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_RPi_main\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_RPi_main\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_main\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "HomeAssistant",
   "type": "logs",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 46 },
   "targets": [
    {
     "expr": "{host=\"raspberrypi\", container_name=\"home-assistant\"}"
    }
   ]
  },
  {
   "title": "Other Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{host=\"raspberrypi\"}"
    }
   ]
  },
  {
   "title": "Picocluster Raspberry Pi (Kubernetes master)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_RPi_pc0\"} - node_boot_time_seconds{job=\"node_exporter_RPi_pc0\"}"
    }
   ]
  },
  {
   "title": "CPU (5min)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc0\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc0\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc0\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Kubernetes Dashboard",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "targets": [
    {
     "expr": "{host=\"pc0\", filename=~\".*dashboard.*\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"node_exporter_RPi_pc0\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_RPi_pc0\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM (5min)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_RPi_pc0\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc0\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc0\"}"
    }
   ]
  },
  {
   "title": "RAM (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc0\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc0\"} - node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc0\"} - (node_memory_Cached_bytes{job=\"node_exporter_RPi_pc0\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc0\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_RPi_pc0\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc0\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc0\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_RPi_pc0\"} - node_memory_SwapFree_bytes{job=\"node_exporter_RPi_pc0\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Control Plane Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 68 },
   "targets": [
    {
     "expr": "{host=\"pc0\",filename=~\".*kube-system.*\"}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc0\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc0\"})"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_RPi_pc0\",device=\"/dev/root\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_RPi_pc0\",device=\"/dev/root\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_RPi_pc0\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_pc0\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "Picocluster Raspberry Pi (Kubernetes worker 1)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_RPi_main\"} - node_boot_time_seconds{job=\"node_exporter_RPi_main\"}"
    }
   ]
  },
  {
   "title": "CPU (5min)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc1\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc1\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc1\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Top CPU Consumers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, cpu_usage{instance=\"192.168.1.240:9091\",exported_instance=\"pc1\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"node_exporter_RPi_pc1\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_RPi_pc1\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM (5min)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_RPi_pc1\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc1\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc1\"}"
    }
   ]
  },
  {
   "title": "RAM (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc1\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc1\"} - node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc1\"} - (node_memory_Cached_bytes{job=\"node_exporter_RPi_pc1\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc1\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_RPi_pc1\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc1\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc1\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_RPi_pc1\"} - node_memory_SwapFree_bytes{job=\"node_exporter_RPi_pc1\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Top Memory Consumers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, memory_usage{instance=\"192.168.1.240:9091\",exported_instance=\"pc1\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc1\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc1\"})"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_RPi_pc1\",device=\"/dev/root\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_RPi_pc1\",device=\"/dev/root\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_RPi_pc1\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_pc1\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "PiHole",
   "type": "logs",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 99 },
   "targets": [
    {
     "expr": "{host=~\"pc.*\", filename=~\".*pihole.*\"}"
    }
   ]
  },
  {
   "title": "NGINX Ingress",
   "type": "logs",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "{host=~\"pc.*\", filename=~\"in\"}"
    }
   ]
  },
  {
   "title": "Picocluster Raspberry Pi (Kubernetes worker 2)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_RPi_pc2\"} - node_boot_time_seconds{job=\"node_exporter_RPi_pc2\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc2\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc2\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc2\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Top CPU Consumers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, cpu_usage{instance=\"192.168.1.240:9091\", exported_instance=\"pc2\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"node_exporter_RPi_pc2\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 115 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_RPi_pc2\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM (5min)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_RPi_pc2\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc2\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc2\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc2\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc2\"} - node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc2\"} - (node_memory_Cached_bytes{job=\"node_exporter_RPi_pc2\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc2\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_RPi_pc2\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc2\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc2\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_RPi_pc2\"} - node_memory_SwapFree_bytes{job=\"node_exporter_RPi_pc2\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Top Memory Consumers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 119 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, memory_usage{instance=\"192.168.1.240:9091\", exported_instance=\"pc2\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc2\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc2\"})"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_RPi_pc2\",device=\"/dev/root\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_RPi_pc2\",device=\"/dev/root\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_RPi_pc2\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_pc2\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "Trello Groomer (Media)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 127 },
   "targets": [
    {
     "expr": "{host=~\"pc.*\", filename=~\".*trello-groomer-media.*\"}"
    }
   ]
  },
  {
   "title": "Trello Groomer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 132 },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "pidfile",
       "operator": "=",
       "value": "/home/picocluster/Volumes/trello-groomer-cache/pid.todo"
      }
     ]
    },
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_data" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "pidfile",
       "operator": "=",
       "value": "/home/picocluster/Volumes/trello-groomer-cache/pid.todo"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "pidfile",
       "operator": "=",
       "value": "/home/picocluster/Volumes/trello-groomer-cache/pid.media"
      }
     ]
    }
   ]
  },
  {
   "title": "Trello Groomer (Work)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 134 },
   "targets": [
    {
     "expr": "{host=~\"pc.*\", filename=~\".*trello-groomer-work.*\"}"
    }
   ]
  },
  {
   "title": "Trello Groomer (ToDo)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "{host=~\"pc.*\", filename=~\".*trello-groomer-todo.*\"}"
    }
   ]
  },
  {
   "title": "Desktop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_desktop\"} - node_boot_time_seconds{job=\"node_exporter_desktop\"}"
    }
   ]
  },
  {
   "title": "CPU (5min)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_desktop\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_desktop\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_desktop\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Top CPU Consumers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 149 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, cpu_usage{job=\"node_exporter_desktop\"})",
     "legendFormat": "{{process}} ({{pid}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_desktop\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}",
     "legendFormat": "{{ chip }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 153 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_desktop\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{uuid=\"$gpu\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "nvidia_smi_gpu_info{uuid=\"$gpu\"}",
     "legendFormat": "driver: {{driver_version}}"
    }
   ]
  },
  {
   "title": "GPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{uuid=\"$gpu\"}",
     "legendFormat": "Memory Utilization (%)"
    },
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"$gpu\"}",
     "legendFormat": "Utilization (%)"
    }
   ]
  },
  {
   "title": "Top Memory Consumers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 156 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, memory_usage{job=\"node_exporter_desktop\"})",
     "legendFormat": "{{process}} ({{pid}})"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "gauge",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_watts{uuid=\"$gpu\"}",
     "legendFormat": "Power Draw (W)"
    },
    {
     "expr": "nvidia_smi_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "Temperature (C)"
    }
   ]
  },
  {
   "title": "Disk (D) Used, 30 Days",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_desktop\",device!~'rootfs',mountpoint=\"/mnt/D\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_desktop\",device!~'rootfs',mountpoint=\"/mnt/D\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_desktop\",device!~'rootfs',mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_desktop\",device!~'rootfs',mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "GPU VRAM Allocation %",
   "type": "gauge",
   "description": "Total memory allocated by active contexts / Total installed GPU memory.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{uuid=\"$gpu\"} / nvidia_smi_memory_total_bytes{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization %",
   "type": "gauge",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "RAM (5min)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_desktop\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_desktop\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_desktop\"}"
    }
   ]
  },
  {
   "title": "RAM (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_desktop\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_desktop\"} - node_memory_MemFree_bytes{job=\"node_exporter_desktop\"} - (node_memory_Cached_bytes{job=\"node_exporter_desktop\"} + node_memory_Buffers_bytes{job=\"node_exporter_desktop\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_desktop\"} + node_memory_Buffers_bytes{job=\"node_exporter_desktop\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_desktop\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_desktop\"} - node_memory_SwapFree_bytes{job=\"node_exporter_desktop\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_desktop\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_main\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "Disk (D)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/D\",fstype!=\"rootfs\",job=\"node_exporter_desktop\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/mnt/D\",fstype!=\"rootfs\",job=\"node_exporter_desktop\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_desktop\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_desktop\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}