---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/sthinds/Volumes/calibre:/config
      - /home/sthinds/data/Documents:/books/Documents
      - /home/sthinds/data/Literature:/books/Literature
    ports:
      - 8093:8080
      - 8081:8081
    restart: unless-stopped
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/caliber-web:calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /home/sthinds/Volumes/calibre:/config
      - /home/sthinds/data/Documents:/books/Documents
      - /home/sthinds/data/Literature:/books/Literature
    ports:
      - 8083:8083
    restart: unless-stopped