{
 "title": "Resource Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cpu_usage" }
   ]
  },
  { "title": "NAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_openmediavault\"} - node_boot_time_seconds{job=\"node_exporter_openmediavault\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_openmediavault\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_openmediavault\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_openmediavault\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_openmediavault\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "{host=\"openmediavault.local\", container_name=\"nextcloud-app\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_openmediavault\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}",
     "legendFormat": "{{ chip }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_openmediavault\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_openmediavault\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_openmediavault\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_openmediavault\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_openmediavault\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_openmediavault\"} - node_memory_MemFree_bytes{job=\"node_exporter_openmediavault\"} - (node_memory_Cached_bytes{job=\"node_exporter_openmediavault\"} + node_memory_Buffers_bytes{job=\"node_exporter_openmediavault\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_openmediavault\"} + node_memory_Buffers_bytes{job=\"node_exporter_openmediavault\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_openmediavault\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_openmediavault\"} - node_memory_SwapFree_bytes{job=\"node_exporter_openmediavault\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk (O)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/srv/dev-disk-by-label-data\",fstype!=\"rootfs\",job=\"node_exporter_openmediavault\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/srv/dev-disk-by-label-data\",fstype!=\"rootfs\",job=\"node_exporter_openmediavault\"})"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_openmediavault\",device!~'rootfs',mountpoint=\"/srv/dev-disk-by-label-data\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_openmediavault\",device!~'rootfs',mountpoint=\"/srv/dev-disk-by-label-data\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_openmediavault\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_main\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  { "title": "Gateway Raspberry Pi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_RPi_main\"} - node_boot_time_seconds{job=\"node_exporter_RPi_main\"}"
    }
   ]
  },
  {
   "title": "CPU (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_main\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_main\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_main\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc0\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_RPi_pc0\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_RPi_pc0\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_RPi_pc0\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc0\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_RPi_main\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_RPi_main\"})"
    }
   ]
  },
  {
   "title": "RAM (24hr)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_main\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_main\"} - node_memory_MemFree_bytes{job=\"node_exporter_RPi_main\"} - (node_memory_Cached_bytes{job=\"node_exporter_RPi_main\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_main\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_RPi_main\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_main\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_RPi_main\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_RPi_main\"} - node_memory_SwapFree_bytes{job=\"node_exporter_RPi_main\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_RPi_main\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_main\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_main\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_main\"})"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_RPi_main\",device=\"/dev/root\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_RPi_main\",device=\"/dev/root\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_RPi_main\", chip=\"thermal_thermal_zone0\", sensor=\"temp0\"}",
     "legendFormat": "{{ chip }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_RPi_main\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc0\"}"
    }
   ]
  },
  {
   "title": "Picocluster Raspberry Pi (master)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_RPi_pc0\"} - node_boot_time_seconds{job=\"node_exporter_RPi_pc0\"}"
    }
   ]
  },
  {
   "title": "CPU (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc0\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc0\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc0\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_main\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_RPi_pc0\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc0\"})"
    }
   ]
  },
  {
   "title": "RAM (24hr)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc0\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc0\"} - node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc0\"} - (node_memory_Cached_bytes{job=\"node_exporter_RPi_pc0\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc0\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_RPi_pc0\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc0\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc0\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_RPi_pc0\"} - node_memory_SwapFree_bytes{job=\"node_exporter_RPi_pc0\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_RPi_pc0\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_pc0\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc0\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc0\"})"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_RPi_pc0\",device=\"/dev/root\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_RPi_pc0\",device=\"/dev/root\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"node_exporter_RPi_pc0\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_RPi_pc0\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc0\"}"
    }
   ]
  },
  {
   "title": "Picocluster Raspberry Pi (worker 1)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_RPi_main\"} - node_boot_time_seconds{job=\"node_exporter_RPi_main\"}"
    }
   ]
  },
  {
   "title": "CPU (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc1\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc1\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc1\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc1\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_RPi_pc1\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc1\"})"
    }
   ]
  },
  {
   "title": "RAM (24hr)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc1\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc1\"} - node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc1\"} - (node_memory_Cached_bytes{job=\"node_exporter_RPi_pc1\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc1\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_RPi_pc1\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc1\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc1\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_RPi_pc1\"} - node_memory_SwapFree_bytes{job=\"node_exporter_RPi_pc1\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_RPi_pc1\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_pc1\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc1\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc1\"})"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_RPi_pc1\",device=\"/dev/root\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_RPi_pc1\",device=\"/dev/root\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"node_exporter_RPi_pc1\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_RPi_pc1\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc1\"}"
    }
   ]
  },
  {
   "title": "Picocluster Raspberry Pi (worker 2)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_RPi_pc2\"} - node_boot_time_seconds{job=\"node_exporter_RPi_pc2\"}"
    }
   ]
  },
  {
   "title": "CPU (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc2\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc2\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc2\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_RPi_pc2\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_RPi_pc2\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc2\"})"
    }
   ]
  },
  {
   "title": "RAM (24hr)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc2\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc2\"} - node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc2\"} - (node_memory_Cached_bytes{job=\"node_exporter_RPi_pc2\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc2\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_RPi_pc2\"} + node_memory_Buffers_bytes{job=\"node_exporter_RPi_pc2\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_RPi_pc2\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_RPi_pc2\"} - node_memory_SwapFree_bytes{job=\"node_exporter_RPi_pc2\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_RPi_pc2\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_pc2\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc2\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_RPi_pc2\"})"
    }
   ]
  },
  {
   "title": "Disk (O) Used, 30 Days",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_RPi_pc2\",device=\"/dev/root\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_RPi_pc2\",device=\"/dev/root\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"node_exporter_RPi_pc2\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_RPi_pc2\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_RPi_pc2\"}"
    }
   ]
  },
  { "title": "Desktop", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_desktop\"} - node_boot_time_seconds{job=\"node_exporter_desktop\"}"
    }
   ]
  },
  {
   "title": "CPU (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_desktop\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_desktop\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_desktop\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU (24hr)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy IO-Wait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_desktop\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM (5min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_exporter_desktop\"} * 100) / node_memory_MemTotal_bytes{job=\"node_exporter_desktop\"})"
    }
   ]
  },
  {
   "title": "RAM (24hr)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_desktop\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_desktop\"} - node_memory_MemFree_bytes{job=\"node_exporter_desktop\"} - (node_memory_Cached_bytes{job=\"node_exporter_desktop\"} + node_memory_Buffers_bytes{job=\"node_exporter_desktop\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_desktop\"} + node_memory_Buffers_bytes{job=\"node_exporter_desktop\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_desktop\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_desktop\"} - node_memory_SwapFree_bytes{job=\"node_exporter_desktop\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter_desktop\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_exporter_RPi_main\"}[5m])*8",
     "legendFormat": "trans {{device}}}"
    }
   ]
  },
  {
   "title": "Disk (D)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/D\",fstype!=\"rootfs\",job=\"node_exporter_desktop\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/mnt/D\",fstype!=\"rootfs\",job=\"node_exporter_desktop\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_desktop\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",job=\"node_exporter_desktop\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk (D) Used, 30 Days",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_desktop\",device!~'rootfs',mountpoint=\"/mnt/D\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_desktop\",device!~'rootfs',mountpoint=\"/mnt/D\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_desktop\",device!~'rootfs',mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_desktop\",device!~'rootfs',mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_desktop\", chip=\"platform_coretemp_0\", sensor=\"temp1\"}",
     "legendFormat": "{{ chip }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_desktop\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_desktop\"}"
    }
   ]
  }
 ]
}