global:
  scrape_interval: 15s
  #evaluation_interval: 15s

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#            #- alertmanager:9093

#rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.1.245:9090"] # localhost
  - job_name: "node_exporter_openmediavault"
    static_configs:
      - targets: [
          # localhost
	  "192.168.1.245:9100",
          "192.168.1.245:9091"
        ]
  - job_name: "node_exporter_RPi_pc0"
    static_configs:
      - targets: [
          # TODO: DNS!!! pc0
          "192.168.1.240:9100",
          "192.168.1.240:9091"
        ]
  - job_name: "node_exporter_RPi_pc1"
    static_configs:
      # TODO: DNS!!! pc1
      - targets: ["192.168.1.241:9100"]
  - job_name: "node_exporter_RPi_pc2"
    static_configs:
      # TODO: DNS!!! pc2
      - targets: ["192.168.1.242:9100"]
  - job_name: "node_exporter_RPi_main"
    static_configs:
      - targets: [
          # TODO: DNS!!! home.assistant
          "192.168.1.243:9100",
          "192.168.1.243:9091"
        ]
  - job_name: "node_exporter_desktop"
    static_configs:
      - targets: [
          # TODO: DNS!!! sthinds.local
          "192.168.1.235:9100",
          "192.168.1.235:9091",
          "192.168.1.235:9835",
          "192.168.1.235:9836"
        ]
